// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.event;

//
// IDL:iris.edu/Fissures/IfEvent/Magnitude:1.0
//
/**
 * Holds a Magnitude estimate for an origin
 **/

final public class Magnitude 
{

    public
    Magnitude(String type,
              float value,
              String contributor)
    {
        this.type = type;
        this.value = value;
        this.contributor = contributor;
    }
    
    /**
     * For hibernate
     */
    Magnitude() {}

    public String type;
    public float value;
    public String contributor;
    
    public String toString() {
    	return value+" "+type;
    }
}
