// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.event;

//
// IDL:iris.edu/Fissures/IfEvent/NoPreferredOrigin:1.0
//
/***/

final public class NoPreferredOrigin extends Exception
{
    public
    NoPreferredOrigin()
    {
        super();
    }

    public
    NoPreferredOrigin(String reason)
    {
        super(reason);
    }
}
