// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.common;

//
// IDL:iris.edu/Fissures/FissuresException:1.0
//
/** The FissuresException is defined as a general exception to be
 *used only when a more specific exceptions do not exist for the
 *occuring exception.
 **/

final public class FissuresException extends Exception
{

    public
    FissuresException(String reason)
    {
        super(reason);
    }
    


}
