// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.common;

//
// IDL:iris.edu/Fissures/LocationType:1.0
//
/** Whether the latitude is measured as distance in degrees along
 *the surface, GEOGRAPHIC, or as an angle from the center of the
 *earth. This is essentially a first order ellipticity correction.*/

final public class LocationType 
{
    private static LocationType [] values_ = new LocationType[2];
    private int value_;

    public final static int _GEOGRAPHIC = 0;
    public final static LocationType GEOGRAPHIC = new LocationType(_GEOGRAPHIC);
    public final static int _GEOCENTRIC = 1;
    public final static LocationType GEOCENTRIC = new LocationType(_GEOCENTRIC);

    protected
    LocationType(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static LocationType
    from_int(int value)
    {
        return values_[value];
    }
}
