// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.common;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterRef:1.0
//
/***/

final public class ParameterRef 
{

    public
    ParameterRef(String a_id,
                 String creator)
    {
        this.a_id = a_id;
        this.creator = creator;
    }

    public String a_id;
    public String creator;
}
