// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.common;

import java.io.Serializable;

import edu.sc.seis.seisFile.DonutArea;

//
// IDL:iris.edu/Fissures/PointDistanceArea:1.0
//
/***/

public class PointDistanceAreaImpl extends DonutArea implements Area
{

    public QuantityImpl min_distance;
    public QuantityImpl max_distance;

    public PointDistanceAreaImpl(float latitude,
                 float longitude,
                 QuantityImpl min_distance,
                 QuantityImpl max_distance) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.min_distance = min_distance;
    this.max_distance = max_distance;
    this.minradius = (float) min_distance.getValue(UnitImpl.DEGREE);// wrong if in km
    this.maxradius = (float) max_distance.getValue(UnitImpl.DEGREE);
    }

    protected PointDistanceAreaImpl() {

    }

    public static Serializable createEmpty() {
        return new PointDistanceAreaImpl();
    }

    public String toString() {
        return "PointDistance ("+latitude+","+longitude+") from "+minradius+" to "+maxradius;
    }
    

}
