// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

//
// IDL:iris.edu/Fissures/Plottable:1.0
//
/** Holds a pixel-ated timeseries or any type of line to be plotted 
 *on a display. */

final public class Plottable 
{
    public
    Plottable()
    {
    }

    public
    Plottable(int[] x_coor,
              int[] y_coor)
    {
        this.x_coor = x_coor;
        this.y_coor = y_coor;
    }

    public int[] x_coor;
    public int[] y_coor;
}
