// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

//
// IDL:iris.edu/Fissures/IfTimeSeries/TimeSeriesType:1.0
//
/***/

final public class TimeSeriesType 
{
    private static TimeSeriesType [] values_ = new TimeSeriesType[5];
    private int value_;

    public final static int _TYPE_SHORT = 0;
    public final static TimeSeriesType TYPE_SHORT = new TimeSeriesType(_TYPE_SHORT);
    public final static int _TYPE_LONG = 1;
    public final static TimeSeriesType TYPE_LONG = new TimeSeriesType(_TYPE_LONG);
    public final static int _TYPE_FLOAT = 2;
    public final static TimeSeriesType TYPE_FLOAT = new TimeSeriesType(_TYPE_FLOAT);
    public final static int _TYPE_DOUBLE = 3;
    public final static TimeSeriesType TYPE_DOUBLE = new TimeSeriesType(_TYPE_DOUBLE);
    public final static int _TYPE_ENCODED = 4;
    public final static TimeSeriesType TYPE_ENCODED = new TimeSeriesType(_TYPE_ENCODED);

    protected
    TimeSeriesType(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static TimeSeriesType
    from_int(int value)
    {
        return values_[value];
    }
}
