// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

import edu.sc.seis.sod.model.station.ChannelId;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/VectorComponent:1.0
//
/***/

final public class VectorComponent 
{
    public
    VectorComponent()
    {
    }

    public
    VectorComponent(ChannelId channel,
                    TimeSeriesDataSel data)
    {
        this.channel = channel;
        this.data = data;
    }

    public ChannelId channel;
    public TimeSeriesDataSel data;
}
