// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.Orientation;
import edu.sc.seis.sod.model.common.QuantityImpl;

//
// IDL:iris.edu/Fissures/IfNetwork/OrientationRange:1.0
//
/***/

public class OrientationRangeImpl 
{

    /***/

    public Orientation center;

    //
    // IDL:iris.edu/Fissures/IfNetwork/OrientationRange/angular_distance:1.0
    //
    /***/

    public QuantityImpl angular_distance;


    
	protected OrientationRangeImpl() {
    }

    public static OrientationRangeImpl createEmpty() {
	return new OrientationRangeImpl();
    }

    public  OrientationRangeImpl(Orientation center,
                                 QuantityImpl angular_distance) {
        this.center = center;
        this.angular_distance =  angular_distance;
    }

}
