// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.SamplingImpl;

//
// IDL:iris.edu/Fissures/IfNetwork/SamplingRange:1.0
//
/***/

public class SamplingRangeImpl 
{

    /***/

    public SamplingImpl min;

    //
    // IDL:iris.edu/Fissures/IfNetwork/SamplingRange/max:1.0
    //
    /***/

    public SamplingImpl max;
    
	protected SamplingRangeImpl() {
    }

    public static SamplingRangeImpl createEmpty() {
	return new SamplingRangeImpl();
    }

    public SamplingRangeImpl(SamplingImpl min,
                             SamplingImpl max) {
        this.min = min;
        this.max = max;
    }

}
